name: build
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Build Nagios Plugin
        run: |
          GOOS=linux GOARCH=amd64 go build -o ./dist/check_wp_status

      - name: Upload Nagios Plugin release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/check_wp_status
          asset_name: check_wp_status
          tag: ${{ github.ref_name }}